# Generated by Django 5.1.1 on 2024-09-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_user_remove_book_finished_remove_book_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_year',
            field=models.PositiveIntegerField(default='0000'),
        ),
    ]
